### ISSUE TITLE
Ionic 7 + Angular 16 + Capacitor 5

### ISSUE THREAD

**Issue by OversoftEdu** [houseninjadojo/capacitor-mixpanel#178]
Hi everyone, the plugin does not work with Ionic 7, Angular 16 and Capacitor 5

**Comment by OversoftEdu** [comment]
@mileszim you know anything about this?

**Comment by tetsuwanadam** [comment]
@OversoftEdu It will be helpful if you provide more context about how exactly it isn't working (error messages, etc).

**Comment by FrancescoPaiola** [comment]
Made a [pull request](https://github.com/houseninjadojo/capacitor-mixpanel/pull/241) to support capacitor 5.

**Comment by rgustavsson** [comment]
Hey @FrancescoPaiola !
How do you integrate with mixpanel with Capacitor 5 at the moment? Do you use a specific fork?
