### ISSUE TITLE
Update dependencies to support Capacitor 5

### ISSUE THREAD

**Issue by tetsuwanadam** [houseninjadojo/capacitor-mixpanel#181]
Can you update the dependencies from Capacitor v4 to v5?
Also might be a good idea to set the plugin version to 5 to match the Capacitor version.

**Comment by ciekawy** [comment]
why this is closed? I assume "cannot reproduce" means this plugin is supposed to work with capacitor 5+. The issue is IMO still valid because of this:

<img width="656" alt="image" src="https://github.com/houseninjadojo/capacitor-mixpanel/assets/2847952/3307c099-a6cd-45b0-a59c-6287c8919ce4">

**Comment by FrancescoPaiola** [comment]
Made a [pull request](https://github.com/houseninjadojo/capacitor-mixpanel/pull/241) to support capacitor 5.
