### ISSUE TITLE
Mixpanel.track not registering if properties includes non-string values

### ISSUE THREAD

**Issue by tetsuwanadam** [houseninjadojo/capacitor-mixpanel#2]
Hi, I noticed that Mixpanel.track() won't send the event and sometimes crashes my Ionic 6 app if the properties object contains non-string values. So for example this works fine:
```
Mixpanel.track({
	event: 'my event',
	properties: {
		test: '1'  // string works fine
	}
});
```

But this doesn't:
```
Mixpanel.track({
	event: 'my event',
	properties: {
		test: 1  // number, boolean, or object won't work
	}
});
```

Here's some info from my package.json. Let me know if you need any more info.

```
  "dependencies": {
    "@capacitor/app": "^1.0.2",
    "@capacitor/core": "^3.1.2",
    "@capacitor/ios": "^3.1.2",
    "@houseninja/capacitor-mixpanel": "^0.0.12",
    "@ionic/core": "^6.0.1",
    "@ionic/vue": "^6.0.1",
    "@ionic/vue-router": "^6.0.1",
    "vue": "^3.2.26",
    "vue-router": "^4.0.12"
  },
```

Thanks for making and sharing this btw, I was super stoked to find it!

**Comment by mileszim** [comment]
thanks for the bug report! this is on my radar too, should have a fix up soon

**Comment by mileszim** [comment]
@tetsuwanadam ok try this one out

**Comment by tetsuwanadam** [comment]
Events with non-string properties still aren't showing up in Mixpanel. Events with string properties only are registering fine.

I believe events that don't have the properties parameter (like below) weren't sending as well, so you might want to look into that :) Thanks!
`Mixpanel.track({event: 'Test event'})`
