### ISSUE TITLE
@capacitor/core

### ISSUE THREAD

**Issue by rgustavsson** [houseninjadojo/capacitor-mixpanel#292]
Hey!

Do you intend to upgrade @capacitor/core to a later version?
We're running on cap 5 and can't use this package after the upgrade..

Thanks for a great plugin!

**Comment by reslear** [comment]
hi @mileszim any news?
i found already solution https://github.com/houseninjadojo/capacitor-mixpanel/pull/276

**Comment by reslear** [comment]
any news?
