### ISSUE TITLE
"Cannot resolve symbol 'CapConfig'" error when building for Android

### ISSUE THREAD

**Issue by tetsuwanadam** [houseninjadojo/capacitor-mixpanel#5]
Hi, I'm trying to build for Android using Ionic 6 and getting this error from line 17 of src/main/java/co/houseninja/plugins/mixpanel/MixpanelPlugin.java:
Cannot resolve symbol 'CapConfig'

Here's the output from info info in case it helps:
```
Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.10

Capacitor:

   Capacitor CLI      : 3.4.2
   @capacitor/android : 3.4.2
   @capacitor/core    : 3.4.2
   @capacitor/ios     : 3.4.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.1.0 (/usr/local/bin/node)
   npm    : 7.24.1
   OS     : macOS Big Sur
```

Thanks!

**Comment by tetsuwanadam** [comment]
This fixes a few build errors and gets it working nicely on my Android device :)
https://github.com/houseninjadojo/capacitor-mixpanel/pull/6

**Comment by mileszim** [comment]
thank you!
