### ISSUE TITLE
cannot find 'getConfig' in scope

### ISSUE THREAD

**Issue by brianstanley** [houseninjadojo/capacitor-mixpanel#97]
Hi!
After update of the library I get this error always when I try to build the app for iOS
![Captura de Pantalla 2023-02-17 a la(s) 15 44 45](https://user-images.githubusercontent.com/1711851/219757782-fa2c0106-5a83-40d6-b7df-a9cf398ae385.png)

<img width="855" alt="Captura de Pantalla 2023-02-17 a la(s) 15 43 46" src="https://user-images.githubusercontent.com/1711851/219757636-d64b4a44-121d-4d9e-911e-a7a431fa9bec.png">

**Comment by mileszim** [comment]
What version of Capacitor are you on?
